[package]
name = "day-4"
version = "0.1.0"
authors = ["Nathan Kleyn <nathan@nathankleyn.com>"]

[dependencies]
chrono = "0.4.6"
itertools = "0.7.11"
lazy_static = "1.2.0"
multimap = "0.4.0"
regex = "1.1.0"
